package com.appspro.mobile.model.module;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 10 18:41:32 GMT+03:00 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XXEmployeeInfo1.
     * @return XXEmployeeInfo1
     */
    public ViewObjectImpl getXXEmployeeInfo1() {
        return (ViewObjectImpl)findViewObject("XXEmployeeInfo1");
    }
}
